# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
      validate_only: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      json_key_data: Base64.decode64(ENV["PLAY_STORE_CREDENTIALS"]),
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
